name: Run integration tests - Demo 1 - Check Suit

on:
  workflow_call:

jobs:
  deploy-to-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run integration tests
        run: |
          echo "Run integration tests - Demo 1 - Check Suit"
